//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartLab.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Smart_LabEntities : DbContext
    {
        public Smart_LabEntities()
            : base("name=Smart_LabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Patient_Tbl> Patient_Tbl { get; set; }
        public virtual DbSet<Doctor_Tbl> Doctor_Tbl { get; set; }
    
        public virtual ObjectResult<spGetProcdure_Result> spGetProcdure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetProcdure_Result>("spGetProcdure");
        }
    }
}
