//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartLab.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Tbl
    {
        public string PatientID { get; set; }
        public string PatientFName { get; set; }
        public string PateintLName { get; set; }
        public string PateintNumber { get; set; }
        public string PateintAddress { get; set; }
    }
}
